#!/bin/sh
set -e

BUCKET="$1"
if test -z "$BUCKET"; then
    echo "Error: Need a bucket to deploy the website to."
    exit 1
fi


rm -rf dist
mole --paths assets build dist


# Upload all files to the bucket with no cache-control.
gsutil -m -h 'Cache-Control: public, max-age=86400' rsync -cR \
    dist/ gs://$BUCKET

# Now change the cache-control header of all files except HTML.
gsutil -m setmeta -h 'Cache-Control: no-cache, no-store, must-revalidate' \
    gs://$BUCKET/**/*.html

echo `git rev-parse HEAD` > dist/version
gsutil -m -h 'Cache-Control: no-cache, no-store, must-revalidate' cp \
    dist/version gs://$BUCKET/version
